# Generated by Django 4.1.6 on 2023-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(max_length=300)),
                ('product_color', models.CharField(max_length=30)),
                ('product_available', models.BooleanField(default=True)),
                ('product_discount', models.CharField(max_length=20)),
                ('product_added_date', models.DateTimeField(auto_now=True)),
                ('product_search_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
